-- Einmaliges Backfill: englische Übungsnamen für bereits existierende Pläne,
-- damit die Bildsuche (services/exerciseDb/exerciseImage.ts, free-exercise-db)
-- auch für Altpläne greift. Nur Zeilen ohne name_en werden angefasst → idempotent.

update public.plan_exercises pe
set name_en = m.en
from (values
  ('Ausfallschritte','Lunge'),
  ('Ausfallschritte (abwechselnd)','Bodyweight Walking Lunge'),
  ('Ausfallschritte (alternierend)','Bodyweight Walking Lunge'),
  ('Ausfallschritte (Kurzhantel)','Dumbbell Lunges'),
  ('Ausfallschritte (Langhantel)','Barbell Lunge'),
  ('Ausfallschritte (pro Bein)','Lunge'),
  ('Ausfallschritte Langhantel','Barbell Lunge'),
  ('Bankdrücken','Barbell Bench Press'),
  ('Bankdrücken (Langhantel)','Barbell Bench Press'),
  ('Bankdrücken Langhantel','Barbell Bench Press'),
  ('Bankdrücken mit Langhantel','Barbell Bench Press'),
  ('Beinheben (liegend)','Flat Bench Lying Leg Raise'),
  ('Beinheben auf Bank','Flat Bench Lying Leg Raise'),
  ('Beinpresse','Leg Press'),
  ('Bergsteiger (Mountain Climbers)','Mountain Climbers'),
  ('Bicycle Crunches','Bicycle Crunch'),
  ('Bizeps Curls (Langhantel)','Barbell Curl'),
  ('Bizepscurls Kurzhantel','Dumbbell Bicep Curl'),
  ('Bodyweight Sissy Squat','Sissy Squat'),
  ('Bulgarischer Split Squat','Bulgarian Split Squat'),
  ('Burpees','Burpee'),
  ('Crunches','Crunches'),
  ('Dips an Bank','Bench Dips'),
  ('Einarmiges Rudern mit Hantel','One-Arm Dumbbell Row'),
  ('Einbeinige Gesäßbrücke','Single Leg Glute Bridge'),
  ('Einbeinige Kniebeuge','One Leg Squat'),
  ('Enger Klimmzug Untergriff','Close-Grip Chin-Up'),
  ('Floor Press Langhantel','Barbell Floor Press'),
  ('Frontheben (Band)','Front Dumbbell Raise'),
  ('Frontkniebeuge Langhantel','Front Barbell Squat'),
  ('Glute Bridge (Band)','Glute Bridge'),
  ('Glute Bridge Langhantel','Barbell Glute Bridge'),
  ('Good Mornings','Good Morning'),
  ('Hängendes Beinheben','Hanging Leg Raise'),
  ('Kabelrudern sitzend','Seated Cable Row'),
  ('Klimmzüge','Pullups'),
  ('Klimmzüge Breitgriff','Wide-Grip Pull-Up'),
  ('Kniebeuge (Langhantel)','Barbell Squat'),
  ('Kniebeuge Langhantel','Barbell Squat'),
  ('Kniebeugen','Bodyweight Squat'),
  ('Kniebeugen (Bodyweight oder Kurzhantel)','Bodyweight Squat'),
  ('Kniebeugen (Körpergewicht oder Kurzhanteln)','Bodyweight Squat'),
  ('Kniebeugen (Körpergewicht)','Bodyweight Squat'),
  ('Kniebeugen (Langhantel)','Barbell Squat'),
  ('Kniebeugen (mit Hantel)','Barbell Squat'),
  ('Kniebeugen mit Langhantel','Barbell Squat'),
  ('Kreuzheben (konventionell)','Barbell Deadlift'),
  ('Kreuzheben (Langhantel)','Barbell Deadlift'),
  ('Kreuzheben (Rumänisch)','Romanian Deadlift'),
  ('Kurzhantel-Rudern (pro Arm)','One-Arm Dumbbell Row'),
  ('Kurzhantel-Schulterdrücken','Dumbbell Shoulder Press'),
  ('Kurzhantelrudern (einarmig)','One-Arm Dumbbell Row'),
  ('Langhantel Bizeps Curls','Barbell Curl'),
  ('Langhantel Rudern Untergriff','Reverse Grip Bent-Over Row'),
  ('Langhantelrudern','Bent Over Barbell Row'),
  ('Langhantelrudern (vorgebeugt)','Bent Over Barbell Row'),
  ('Latzug','Wide-Grip Lat Pulldown'),
  ('Latzug (Kabelzug)','Wide-Grip Lat Pulldown'),
  ('Latzug zur Brust','Wide-Grip Lat Pulldown'),
  ('Leg Raises','Leg Raises'),
  ('Liegestütze','Pushups'),
  ('Liegestütze (auf Knien oder Füßen)','Pushups'),
  ('Liegestütze (auf Knien oder Standard)','Pushups'),
  ('Liegestütze Füße Hoch','Decline Push-Up'),
  ('Mountain Climbers','Mountain Climbers'),
  ('Plank','Plank'),
  ('Plank (Boden)','Plank'),
  ('Plank (Unterarmstütz)','Plank'),
  ('Push Press Langhantel','Barbell Push Press'),
  ('Romanian Deadlift','Romanian Deadlift'),
  ('Rudern (Band, sitzend)','Seated Cable Row'),
  ('Rudern (Langhantel)','Bent Over Barbell Row'),
  ('Rudern mit Kurzhantel','One-Arm Dumbbell Row'),
  ('Rudern mit Kurzhanteln','One-Arm Dumbbell Row'),
  ('Rumänisches Kreuzheben mit Langhantel','Romanian Deadlift'),
  ('Russian Twist (Boden)','Russian Twist'),
  ('Russian Twists','Russian Twist'),
  ('Russische Twists','Russian Twist'),
  ('Russische Twists (mit oder ohne Gewicht)','Russian Twist'),
  ('Schrägbankdrücken (Langhantel)','Barbell Incline Bench Press'),
  ('Schulterdrücken','Shoulder Press'),
  ('Schulterdrücken (Kurzhantel)','Dumbbell Shoulder Press'),
  ('Schulterdrücken (Langhantel)','Barbell Shoulder Press'),
  ('Schulterdrücken (stehend, mit Hanteln)','Standing Dumbbell Press'),
  ('Schulterdrücken mit Kurzhanteln','Dumbbell Shoulder Press'),
  ('Seitheben Kurzhantel','Side Lateral Raise'),
  ('Shoulder Press','Shoulder Press'),
  ('Skullcrushers Langhantel','Lying Triceps Press'),
  ('Step-Up (einbeinig)','Dumbbell Step Ups'),
  ('Trizepsdrücken am Kabelzug','Triceps Pushdown'),
  ('Überkopfdrücken (Langhantel stehend)','Standing Military Press'),
  ('Überkopfdrücken (stehend, Langhantel)','Standing Military Press'),
  ('Überkopfdrücken Langhantel','Standing Military Press'),
  ('Überkopfdrücken mit Kurzhanteln','Standing Dumbbell Press'),
  ('Überkopfdrücken mit Langhantel (stehend)','Standing Military Press'),
  ('Wadenheben (einbeinig)','Standing Calf Raises')
) as m(de, en)
where pe.exercise_name = m.de and pe.name_en is null;
